services:
  - type: web
    name: xray-setu
    runtime: python
    rootDir: server
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DEBUG
        value: 0