# Generated by Django 5.2 on 2025-09-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0003_delete_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("patient", "Patient"), ("nurse", "Nurse")],
                default="patient",
                max_length=10,
            ),
        ),
    ]
